Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -21,24 +21,24 @@ jobs:
       run:
         shell: bash
  
-    steps:
-    - name: Checkout
-      uses: actions/checkout@v3
-    - name: Terraform Init
-      run: |
-        terraform init
-    - name: Terraform Validate
-      run: terraform  validate -no-color
-    - name: Terraform Plan
-      run: terraform plan -no-color -input=false
-      continue-on-error: true
-    - name: Terraform Plan Status
-      if: steps.plan.outcome == 'failure'
-      run: exit 1
+#     steps:
+#     - name: Checkout
+#       uses: actions/checkout@v3
+#     - name: Terraform Init
+#       run: |
+#         terraform init
+#     - name: Terraform Validate
+#       run: terraform  validate -no-color
+#     - name: Terraform Plan
+#       run: terraform plan -no-color -input=false
+#       continue-on-error: true
+#     - name: Terraform Plan Status
+#       if: steps.plan.outcome == 'failure'
+#       run: exit 1
       
-    - name: Terraform Apply
-      run: terraform apply -auto-approve -no-color -input=false
-      continue-on-error: true
+#     - name: Terraform Apply
+#       run: terraform apply -auto-approve -no-color -input=false
+#       continue-on-error: true
       
   Terraform_Destroy:
     name: 'TerraformDestroy'
